//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyStatEntities : DbContext
    {
        public MyStatEntities()
            : base("name=MyStatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Administrator> tbl_Administrator { get; set; }
        public virtual DbSet<tbl_ConGroup> tbl_ConGroup { get; set; }
        public virtual DbSet<tbl_Daybook> tbl_Daybook { get; set; }
        public virtual DbSet<tbl_DoneHomework> tbl_DoneHomework { get; set; }
        public virtual DbSet<tbl_Group> tbl_Group { get; set; }
        public virtual DbSet<tbl_Homework> tbl_Homework { get; set; }
        public virtual DbSet<tbl_News> tbl_News { get; set; }
        public virtual DbSet<tbl_TrainingMaterial> tbl_TrainingMaterial { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
