//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrainingMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TrainingMaterial()
        {
            this.tbl_Group = new HashSet<tbl_Group>();
        }
    
        public int IdTrainingMaterial { get; set; }
        public string MatherialType { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string zipFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Group> tbl_Group { get; set; }
    }
}
