//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Homework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Homework()
        {
            this.tbl_DoneHomework = new HashSet<tbl_DoneHomework>();
        }
    
        public int IdHomework { get; set; }
        public int IdUser { get; set; }
        public int IdGroup { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Subject { get; set; }
        public string Theme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DoneHomework> tbl_DoneHomework { get; set; }
        public virtual tbl_Group tbl_Group { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
