//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoneHomework
    {
        public int IdDoneHomework { get; set; }
        public int IdUser { get; set; }
        public int IdHomework { get; set; }
        public Nullable<int> Mark { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string zipFile { get; set; }
    
        public virtual tbl_Homework tbl_Homework { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
