//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrainingMaterial
    {
        public int IdTrainingMaterial { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string MatherialType { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string zipFile { get; set; }
    
        public virtual tbl_Group tbl_Group { get; set; }
    }
}
