//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_News
    {
        public int IdNews { get; set; }
        public int IdAdministrator { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Theme { get; set; }
        public string Text { get; set; }
    
        public virtual tbl_Administrator tbl_Administrator { get; set; }
    }
}
