//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConGroup
    {
        public int IdConGroup { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual tbl_Group tbl_Group { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
